version: "3.9"

services:
  service_a:
    build: ./service_a
    container_name: service_a
    ports:
      - "5000:5000"
    networks:
      - micros_net

  service_b:
    build: ./service_b
    container_name: service_b
    ports:
      - "5001:5000"
    environment:
      SERVICE_A_URL: http://service_a:5000
    depends_on:
      - service_a
    networks:
      - micros_net

networks:
  micros_net: